cache:
  ccache: true

language: c

jobs:
 include:
   - os: linux
     dist: bionic
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - gcc-9
           - ccache
           - ninja-build
           - libevdev-dev
           - libudev-dev
           - libev-dev
     env:
       - MATRIX_EVAL="CC=gcc-9"
   - os: linux
     dist: bionic
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - gcc-8
           - ccache
           - ninja-build
           - libevdev-dev
           - libudev-dev
           - libev-dev
     env:
       - MATRIX_EVAL="CC=gcc-8"
   - os: linux
     dist: bionic
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - gcc-7
           - ccache
           - ninja-build
           - libevdev-dev
           - libudev-dev
           - libev-dev
     env:
       - MATRIX_EVAL="CC=gcc-7 DO_INSTALL=1"
   - os: linux
     dist: bionic
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - sourceline: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
             key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
         packages:
           - clang-11
           - ccache
           - ninja-build
           - libevdev-dev
           - libudev-dev
           - libev-dev
     env:
       - MATRIX_EVAL="CC=clang-11"
   - os: linux
     dist: bionic
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - sourceline: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
             key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
         packages:
           - clang-10
           - ccache
           - ninja-build
           - libevdev-dev
           - libudev-dev
           - libev-dev
     env:
       - MATRIX_EVAL="CC=clang-10"
   - os: linux
     dist: bionic
     addons:
       apt:
         packages:
           - clang
           - ccache
           - ninja-build
           - libevdev-dev
           - libudev-dev
           - libev-dev
     env:
       - MATRIX_EVAL="CC=clang"

before_script:
  - 
before_install:
  - eval "${MATRIX_EVAL}"
  - export "CC=ccache $CC"
script:
  - "./build"
  - "./scripts/check-install"

branches:
  only:
    - staging
    - trying
    - master
    - travis
