[package]
name = "illum-ng"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-udev = "0.2.0"
tokio = { version = "0.2.13", features = ["full"] }
